services:
  api:
    build:
      context: .
      network: host
    container_name: befreeclub-api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
